# Generated by Django 5.1.1 on 2024-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='comments',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lids',
            name='type',
            field=models.IntegerField(choices=[(1, 'yangi'), (2, 'kutilayotgan'), (3, 'shartnoma qilingan'), (4, 'toxtatilgan')], default=1),
        ),
    ]
