# Generated by Django 5.1.1 on 2024-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_university_comments_university_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='futures',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
